#================================================
# Actuator
#================================================
management:
  endpoints:
    # HEALTH ENDPOINT
    health:
      show-details: always
    # ENDPOINTS WEB CONFIGURATION
    web:
      exposure:
        include: health,info,metrics,prometheus
    metrics:
      tags:
        application: ${spring:application:name}
spring:
  jpa:
    defer-datasource-initialization: true
  application:
    name: spring-boot-metrics
  datasource:
    url: "jdbc:h2:mem:mydb"
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: "/h2-console"
info:
  app:
    name: spring-boot-metrics
    description: "Project to study metrics using prometheus and grafana"
    version: 0.0.1
    java:
      version: 11

app:
  monitoring:
    prefix: spring-boot-metrics